### ISSUE TITLE
how can I run this model？QAQ

### ISSUE THREAD

**Issue by ZengWenhao296** [lenow520/Music-Emotion-Recognization-Model#1]
filepath = 'D:\\user\\Downloads\\audio-classification-master\\audio-classification-master\\'
# Set Parameters 
class_count = 4

#load data
X = np.load(filepath+'feat1.npy')
y = np.load(filepath+'label1.npy').ravel()

what data should be put in the filepath？

**Comment by lenow520** [comment]
Hi @[ZengWenhao296](https://github.com/ZengWenhao296)
what I did is to label the music data(1000 songs dataset) and generate each audio's spectrum as the paper I refered. That is how I obtained the "feat1.npy" and "label1.npy".

I hope this answer would help you in anyway.
